[package]
name = "fm-xml-export-exploder"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs_io = "0.1.7"
rayon = "1.10.0"
quick-xml = "0.31.0"
regex = "1.10.4"
clap = { version = "4.5.7", features = ["derive"] }
anyhow = "1.0.86"
strum = { version = "0.26.2", features = ["strum_macros"] }
strum_macros = "0.26.2"

[dev-dependencies]
walkdir = "2.5.0"
insta = "1.39.0"
similar-asserts = "1.5.0"
