[package]
name = "fm-xml-export-exploder"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs_io = "0.1.7"
rayon = "1.10.0"
quick-xml = "0.36.2"
regex = "1.11.0"
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"
strum = { version = "0.26.3", features = ["strum_macros"] }
strum_macros = "0.26.4"

[dev-dependencies]
walkdir = "2.5.0"
insta = "1.41.0"
similar-asserts = "1.6.0"
