pub enum ScriptStep {
    PerformScript,
    GoToPreviousField,
    GoToNextField,
    GoToLayout,
    NewRecordRequest,
    DuplicateRecordRequest,
    DeleteRecordRequest,
    DeleteAllRecords,
    GoToRecordRequestPage,
    GoToField,
    CheckRecord,
    CheckFoundSet,
    UnsortRecords,
    EnterFindMode,
    ShowAllRecords,
    ModifyLastFind,
    OmitRecord,
    OmitMultipleRecords,
    ShowOmittedOnly,
    PerformFind,
    OpenHelp,
    OpenManageDatabase,
    ExitApplication,
    SelectAll,
    EnterBrowseMode,
    IfStart,
    Else,
    IfEnd,
    LoopStart,
    ExitLoopIf,
    LoopEnd,
    CommitRecordRequests,
    SetFieldData,
    FixWindow,
    NewFile,
    AllowUserAbort,
    SetErrorRecording,
    OpenScriptWorkspace,
    Comment,
    HaltScript,
    ReplaceFieldContents,
    Beep,
    SetUseSystemFormats,
    GoToPortalRow,
    CopyRecordRequest,
    FlushCacheToDisk,
    ExitScript,
    OpenSettings,
    CorrectWord,
    SpellingOptions,
    SelectDictionaries,
    EditUserDictionary,
    OpenManageValueLists,
    OpenSharing,
    OpenFileOptions,
    AllowFormattingBar,
    OpenHosts,
    CloseWindow,
    NewWindow,
    IfElse,
    OpenFindReplace,
    OpenManageDataSources,
    SetVariable,
    GoToObject,
    OpenEditSavedFinds,
    OpenManageLayouts,
    OpenManageContainers,
    OpenManageThemes,
    RefreshObject,
    ClosePopover,
    UploadToServer,
    OpenMyApps,
    Unknown,
}

pub fn id_to_script_step(id: &str) -> ScriptStep {
    match id {
        "1" => ScriptStep::PerformScript,
        "2" => ScriptStep::Unknown,
        "3" => ScriptStep::Unknown,
        "4" => ScriptStep::GoToPreviousField,
        "5" => ScriptStep::GoToNextField,
        "6" => ScriptStep::GoToLayout,
        "7" => ScriptStep::NewRecordRequest,
        "8" => ScriptStep::DuplicateRecordRequest,
        "9" => ScriptStep::DeleteRecordRequest,
        "10" => ScriptStep::DeleteAllRecords,
        "15" => ScriptStep::Unknown,
        "16" => ScriptStep::GoToRecordRequestPage,
        "17" => ScriptStep::GoToField,
        "19" => ScriptStep::CheckRecord,
        "20" => ScriptStep::CheckFoundSet,
        "21" => ScriptStep::UnsortRecords,
        "22" => ScriptStep::EnterFindMode,
        "23" => ScriptStep::ShowAllRecords,
        "24" => ScriptStep::ModifyLastFind,
        "25" => ScriptStep::OmitRecord,
        "26" => ScriptStep::OmitMultipleRecords,
        "27" => ScriptStep::ShowOmittedOnly,
        "28" => ScriptStep::PerformFind,
        "32" => ScriptStep::OpenHelp,
        "38" => ScriptStep::OpenManageDatabase,
        "44" => ScriptStep::ExitApplication,
        "50" => ScriptStep::SelectAll,
        "52" => ScriptStep::Unknown,
        "53" => ScriptStep::Unknown,
        "54" => ScriptStep::Unknown,
        "55" => ScriptStep::EnterBrowseMode,
        "58" => ScriptStep::Unknown,
        "68" => ScriptStep::IfStart,
        "69" => ScriptStep::Else,
        "70" => ScriptStep::IfEnd,
        "71" => ScriptStep::LoopStart,
        "72" => ScriptStep::ExitLoopIf,
        "73" => ScriptStep::LoopEnd,
        "75" => ScriptStep::CommitRecordRequests,
        "76" => ScriptStep::SetFieldData,
        "79" => ScriptStep::FixWindow,
        "82" => ScriptStep::NewFile,
        "85" => ScriptStep::AllowUserAbort,
        "86" => ScriptStep::SetErrorRecording,
        "88" => ScriptStep::OpenScriptWorkspace,
        "89" => ScriptStep::Comment,
        "90" => ScriptStep::HaltScript,
        "91" => ScriptStep::ReplaceFieldContents,
        "93" => ScriptStep::Beep,
        "94" => ScriptStep::SetUseSystemFormats,
        "99" => ScriptStep::GoToPortalRow,
        "100" => ScriptStep::Unknown,
        "101" => ScriptStep::CopyRecordRequest,
        "102" => ScriptStep::FlushCacheToDisk,
        "103" => ScriptStep::ExitScript,
        "105" => ScriptStep::OpenSettings,
        "106" => ScriptStep::CorrectWord,
        "107" => ScriptStep::SpellingOptions,
        "108" => ScriptStep::SelectDictionaries,
        "109" => ScriptStep::EditUserDictionary,
        "110" => ScriptStep::Unknown,
        "112" => ScriptStep::OpenManageValueLists,
        "113" => ScriptStep::OpenSharing,
        "114" => ScriptStep::OpenFileOptions,
        "115" => ScriptStep::AllowFormattingBar,
        "118" => ScriptStep::OpenHosts,
        "121" => ScriptStep::CloseWindow,
        "122" => ScriptStep::NewWindow,
        "125" => ScriptStep::IfElse,
        "129" => ScriptStep::OpenFindReplace,
        "140" => ScriptStep::OpenManageDataSources,
        "141" => ScriptStep::SetVariable,
        "145" => ScriptStep::GoToObject,
        "149" => ScriptStep::OpenEditSavedFinds,
        "151" => ScriptStep::OpenManageLayouts,
        "156" => ScriptStep::OpenManageContainers,
        "162" => ScriptStep::Unknown,
        "163" => ScriptStep::Unknown,
        "165" => ScriptStep::OpenManageThemes,
        "167" => ScriptStep::RefreshObject,
        "169" => ScriptStep::ClosePopover,
        "170" => ScriptStep::Unknown,
        "171" => ScriptStep::Unknown,
        "172" => ScriptStep::UploadToServer,
        "173" => ScriptStep::Unknown,
        "183" => ScriptStep::OpenMyApps,
        "198" => ScriptStep::Unknown,
        "204" => ScriptStep::Unknown,
        _ => ScriptStep::Unknown,
    }
}
